<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.Google" Version="6.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>
</Project>
